Apply patches
loql-com/firebase-extensions-fork pull request #1
Opened 2023-06-23 09:21 UTC by coehne

2023-07-03 15:29 UTC, AndreasKl commented
LGTM 👍🏻  Vielleicht wäre eine readme cool, die beschreibt, wo man was eintragen muss um den Code zu erweitern...

2023-07-03 15:30 UTC, AndreasKl requested changes
siehe Kommentar

2023-07-03 16:45 UTC, coehne commented
Yes, ich wollte den die ganzen Anweisungen was zu tun und zu ändern ist alle im Main Repo in die Readme packen. Meinst du das sollte ich lieber alles hier rein schreiben was hier zu ändern ist? Weil der Änderungsgrund ja immer im Main Repo sein wird. Dort von wo auch die Skripte aufgerufen werden.

2023-07-04 06:02 UTC, AndreasKl commented
> Yes, ich wollte den die ganzen Anweisungen was zu tun und zu ändern ist alle im Main Repo in die Readme packen. Meinst du das sollte ich lieber alles hier rein schreiben was hier zu ändern ist? Weil der Änderungsgrund ja immer im Main Repo sein wird. Dort von wo auch die Skripte aufgerufen werden.
> 
> EDIT: Mit Main Repo meine ich unser Firebase Main repo und nicht das Base Repo. Da weiß ich selber noch nicht wie man damit umgehen sollte. Würde erstmal garnicht das Base Repo von dem geforked wurde rebasen.

Mhh, da habe ich keine starke Meinunng zu, ich würde das hier dann eher "soweit" möglich unangetastet lassen und die Doku ins functions repo schreiben.

2023-07-04 06:02 UTC, AndreasKl approved these changes

2023-07-05 07:53 UTC, coehne commented
Ja genau, das wollte ich damit sagen :) Communication is hard!

2023-07-05 07:53 UTC, merged